services:
  cloudbeaver:
    image: dbeaver/cloudbeaver
    pull_policy: if_not_present
    restart: unless-stopped
    ports:
      - "4230:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8978"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cloudbeaver-data: